plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

version = '1.0.0'

repositories { mavenCentral() }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}

javafx {
    version = '17.0.2'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'org.example.Main'
}

dependencies {
    implementation ('org.json:json:20240303')
}